name: 'main' 
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test_image_rpi4:
    runs-on: [self-hosted, linux, x64, dut, raspberrypi4]
    steps:
      - name: clean up
        run: rm -fR $BUILDDIR

      - uses: actions/checkout@v4

      - name: create mountpoint
        run: mkdir data

      - name: test 32bit image
        run: >
          ./helpers/control_rig.sh power_off &&
          ./helpers/control_rig.sh sdmux_host &&
          ./helpers/flash_to_rig.sh /mnt/mender_gha/TheYoctoJester/meta-mender-community/scarthgap/build_validation/latest/raspberrypi4/images/core-image-minimal-raspberrypi4.sdimg &&
          ./helpers/simple_run.sh &&
          ./helpers/gather_validation_artifacts.sh

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: raspberrypi4.tar.bz2
          path: output.tar.bz2

  test_image_rpi4-64:
    runs-on: [self-hosted, linux, x64, dut, raspberrypi4]
    steps:
      - name: clean up
        run: rm -fR $BUILDDIR

      - uses: actions/checkout@v4

      - name: create mountpoint
        run: mkdir data

      - name: run 64bit test
        run: >
          ./helpers/control_rig.sh power_off &&
          ./helpers/control_rig.sh sdmux_host &&
          ./helpers/flash_to_rig.sh /mnt/mender_gha/TheYoctoJester/meta-mender-community/scarthgap/build_validation/latest/raspberrypi4-64/images/core-image-minimal-raspberrypi4-64.sdimg &&
          ./helpers/simple_run.sh &&
          ./helpers/gather_validation_artifacts.sh

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: raspberrypi4-64.tar.bz2
          path: output.tar.bz2