name: 'main' 
on:
  push:
    branches:
      - main

jobs:
  test_image_rpi4:
    runs-on: [self-hosted, linux, x64, dut, raspberrypi4]
    steps:
      - name: clean up
        run: rm -fR $BUILDDIR

      - uses: actions/checkout@v4

      - name: create mountpoint
        run: mkdir data

      - name: run 32bit test
        run: ./helpers/flash_to_rig.sh /mnt/mender_gha/TheYoctoJester/for_test/core-image-minimal-raspberrypi4-20241104160415.sdimg

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: raspberrypi4.tar.bz2
          path: output.tar.bz2

  test_image_rpi4-64:
    runs-on: [self-hosted, linux, x64, dut, raspberrypi4]
    steps:
      - name: clean up
        run: rm -fR $BUILDDIR

      - uses: actions/checkout@v4

      - name: create mountpoint
        run: mkdir data

      - name: run 64bit test
        run: ./helpers/flash_to_rig.sh /mnt/mender_gha/TheYoctoJester/for_test/core-image-minimal-raspberrypi4-64-20241104155953.sdimg

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: raspberrypi4-64.tar.bz2
          path: output.tar.bz2